version: '3.8'
services:

  wordpress:
    image: wordpress
    networks: 
      - wordpress
    ports:
      - '${PUB_PORT}:80'
    env_file: 
      - .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_NAME}'
    volumes:
      - wordpress:/var/www/html
      - ./install.php:/usr/src/wordpress/wp-admin/install.php
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M

volumes:
  wordpress:

networks:
  wordpress:
    external: true
