---
- name: Configure server
  hosts: all
  gather_facts: true
  #collections:
  #  - ericsysmin.docker

  tasks:

    - name: Including vars from server.yml
      # ansible.builtin.include_vars doesn't work
      include_vars:
        file: server.yml

    - name: Installing docker
      # ansible.builtin.import_role doesn't work
      import_role:
        name: ericsysmin.docker.docker
      vars:
        docker_storage_driver: aufs
        # Users to docker group
        docker_users: '{{docker_users}}'
      become: true

    - name: Initing docker swarm
      community.general.docker_swarm:
        state: present

    - name: Installing docker-compose
      get_url:
        url: '{{compose_url}}'
        # $(uname -s) = {{ ansible_facts['system'] }}
        # $(uname -m) = {{ ansible_facts['machine'] }}
        dest: '/usr/local/bin/docker-compose'
        mode: 'o+x'
      become: true

    # - name: Container Jenkins implantado
    #   ansible.builtin.command:
    #     argv:
    #       - docker
    #       - ps
    