---
- name: Deploy Wordpress from template
  hosts: all
  gather_facts: false
  vars:
    # app -- git cloned wordpress folder
    # project_name -- destine folder
    - app_split: '{{ app | urlsplit }}'
    - dest_folder: '~/'

  tasks:
    # Destine folder name on server defaults to the source folder name
    # Define project_name to set a different value
    - name: 'Setting project_name'
      ansible.builtin.set_fact:
        project_name: "{{ app_split.path | basename | splitext | first }}"
      when: project_name is not defined

    # Destine folder location defaults to ~/
    # Define project_folder to set a different value
    - name: 'Setting project_folder'
      ansible.builtin.set_fact:
        project_folder: '{{ dest_folder }}{{ project_name }}/'

    - name: 'Copying {{ app }} into {{ project_folder }}'
      ansible.builtin.copy:
        src: '{{ app }}/'
        dest: '{{ project_folder }}'
        mode: '0600'
        force: false

    - name: 'Registering .env variables'
      ansible.builtin.command:
        chdir: '{{ project_folder }}'
        argv:
        - python3
        - -c
        - import dotenv; print(dotenv.dotenv_values())
      register: dotenv_raw

    - name: 'Setting dotenv fact'
      ansible.builtin.set_fact:
        dotenv: '{{ dotenv_raw.stdout | from_yaml }}'

    - name: 'Deploying stack from stack.yml'
      community.general.docker_stack:
        name: '{{ project_name }}'
        compose: '{{ project_folder }}stack.yml'
        state: present
      environment: '{{ dotenv }}'
