---
# ansible-playbook -e '
# git_url=...
# project_name=...
# repo_version=...
# repo_key=...
# ' deploy_app.yml
  
- name: Deploy app from git
  hosts: all
  gather_facts: false
  vars:
    - git_url: false
    #- project_name: false
    - repo_version: HEAD
    - repo_key: false
  
  tasks:

    - name: 'Cloning {{git_url}}'
      ansible.builtin.git:
        repo: '{{git_url}}'
        version: '{{repo_version}}'
        key_file: '{{repo_key}}'
        accept_hostkey: true
        dest: '/tmp/{{project_name}}'
        force: true
      register: clone_result
      until: clone_result is not failed
      retries: 3
      delay: 3

    - name: 'Deploying from docker-compose.yml'
      community.general.docker_compose:
        project_src: /tmp/{{project_name}}
        build: true
        state: present
    
    - name: 'Removing git repository'
      ansible.builtin.file:
        path: '/tmp/{{project_name}}'
        state: absent
    