---
# ansible-playbook -e '
# git_url=...
# project_name=...
# repo_version=...
# repo_key=...
# ' deploy_app.yml
  
- name: Deploy app from git
  hosts: all
  gather_facts: false
  vars:
    # git_url
    - project_name: "{{ git_url | urlsplit('path') | basename | splitext | first }}"
    - repo_version: 'HEAD'
    - repo_key: ''
    - base_dir: '/tmp/'
    - dest_folder: '{{ base_dir }}{{ project_name }}'
  
  tasks:

    - name: 'Cloning {{ git_url }} into {{ dest_folder }}'
      ansible.builtin.git:
        repo: '{{ git_url }}'
        version: '{{ repo_version }}'
        key_file: '{{ repo_key }}'
        accept_hostkey: true
        dest: '{{ dest_folder }}'
        umask: '0077'
        force: true
      register: clone_result
      until: clone_result is not failed
      retries: 3
      delay: 3

    - name: 'Deploying from docker-compose.yml'
      community.general.docker_compose:
        project_src: '{{ dest_folder }}'
        build: true
        state: present
    
    - name: 'Removing git repository'
      ansible.builtin.file:
        path: '{{ dest_folder }}'
        state: absent
    