version: '3.8'
services:

  db:
    image: 'mysql:5.7'
    networks:
      - wordpress
    ports:
      - '3306:3306'
      #- '33060:33060'
    environment:
      MYSQL_ROOT_PASSWORD: '${ROOT_PASSWORD}'
    volumes:
      - db:/var/lib/mysql
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 300M
        limits:
          cpus: '0.5'
          memory: 500M

volumes:
  db:

networks:
  wordpress:
    external: true
